return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      flavour = "mocha",
      background = {
        light = "latte",
        dark = "mocha",
      },
      transparent_background = false,
      show_end_of_buffer = false,
      term_colors = false,
      dim_inactive = {
        enabled = false,
        shade = "dark",
        percentage = 0.15,
      },
      no_italic = false,
      no_bold = false,
      no_underline = false,
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
      },
      color_overrides = {
        mocha = {
          base = "#101113",
          mantle = "#101113",
          crust = "#101113",
          text = "#9f9e99",
          subtext1 = "#787487",
          subtext0 = "#554A62",
          overlay2 = "#9f9e99",
          overlay1 = "#787487",
          overlay0 = "#554A62",
          surface2 = "#4a4253",
          surface1 = "#3a3545",
          surface0 = "#2a2635",
          lavender = "#8288A0",
          blue = "#697a9a",
          sapphire = "#697a9a",
          sky = "#8288A0",
          teal = "#7a837c",
          green = "#a7d8b0",
          yellow = "#e1ffe5",
          peach = "#ac7f7b",
          maroon = "#93554b",
          red = "#93554b",
          mauve = "#83799C",
          pink = "#997e95",
          flamingo = "#ac7f7b",
          rosewater = "#e1ffe5",
        },
      },
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        notify = false,
        mini = {
          enabled = true,
          indentscope_color = "",
        },
      },
    })
    vim.cmd.colorscheme("catppuccin")
  end,
}
